name: repocheck

on:
  pull_request:
    branches:
      - master
      - "[0-9]+.[0-9]+"

jobs:
  unusedmodules:
    runs-on: ubuntu-latest
    defaults:
      run:
        working directory: .guides/scripts
    steps:
      - run: ./find_unused_modules.py

